## Importing libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data collection

In [2]:
# collecting data from the apples dataset
df = pd.read_csv('Apples.csv')

## Data exploration

In [ ]:
## Checking for the information for example Dtype , null, column labels and non-null objects
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4001 entries, 0 to 4000
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   A_id         4000 non-null   float64
 1   Size         4000 non-null   float64
 2   Weight       4000 non-null   float64
 3   Sweetness    4000 non-null   float64
 4   Crunchiness  4000 non-null   float64
 5   Juiciness    4000 non-null   float64
 6   Ripeness     4000 non-null   float64
 7   Acidity      4001 non-null   object
 8   Quality      4000 non-null   object
dtypes: float64(7), object(2)
memory usage: 281.4+ KB

## Data preprocessing

In [ ]:
# Converts acidity value from an object to numeric value. Coerce handles any errors and we drop the object values.
# The info prompt shows that the acidity value is now in float64 format
df['Acidity'] = pd.to_numeric(df['Acidity'], errors='coerce')

df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4000 entries, 0 to 3999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   A_id         4000 non-null   float64
 1   Size         4000 non-null   float64
 2   Weight       4000 non-null   float64
 3   Sweetness    4000 non-null   float64
 4   Crunchiness  4000 non-null   float64
 5   Juiciness    4000 non-null   float64
 6   Ripeness     4000 non-null   float64
 7   Acidity      4000 non-null   float64
 8   Quality      4000 non-null   object
dtypes: float64(8), object(1)
memory usage: 312.5+ KB

In [7]:
# Setting the seaborn theme for the entire script
sns.set_theme(style='whitegrid', palette='deep')
sns.color_palette('Oranges')

[(0.9955709342560554, 0.8907958477508651, 0.7855132641291811),
 (0.9921568627450981, 0.7769934640522875, 0.5727028066128412),
 (0.9921568627450981, 0.6280507497116494, 0.34226835832372166),
 (0.9648442906574395, 0.47100346020761247, 0.14197616301422528),
 (0.8782929642445213, 0.31990772779700116, 0.024405997693194924),
 (0.6768627450980392, 0.22089965397923875, 0.010749711649365626)]

In [8]:
# Statistical summary
df.describe()

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,1999.500000,-0.503015,-0.989547,-0.470479,0.985478,0.512118,0.498277,0.076877
std,1154.844867,1.928059,1.602507,1.943441,1.402757,1.930286,1.874427,2.110270
min,0.000000,-7.151703,-7.149848,-6.894485,-6.055058,-5.961897,-5.864599,-7.010538
25%,999.750000,-1.816765,-2.011770,-1.738425,0.062764,-0.801286,-0.771677,-1.377424
50%,1999.500000,-0.513703,-0.984736,-0.504758,0.998249,0.534219,0.503445,0.022609
75%,2999.250000,0.805526,0.030976,0.801922,1.894234,1.835976,1.766212,1.510493
max,3999.000000,6.406367,5.790714,6.374916,7.619852,7.364403,7.237837,7.404736

In [ ]:
# exploring columns in the dataset
df.columns

Index(['A_id', 'Size', 'Weight', 'Sweetness', 'Crunchiness', 'Juiciness',
       'Ripeness', 'Acidity', 'Quality'],
      dtype='object')

In [22]:
# Creating a dataframe containing 
data = ['Size', 'Weight', 'Crunchiness', 'Juiciness', 'Ripeness','Acidity']

In [23]:
# Descriptive statistics
ds = pd.DataFrame({
    'Mean': df[data].mean(),
    'Median': df[data].median(),
    'Mode': df[data].mode().iloc[0],
    'Variance': df[data].var(),
    'Standard Deviation': df[data].std(),
    'Skewness': df[data].skew(),
    'Kurtosis': df[data].kurt(),
})

In [24]:
ds.head()

,Mean,Median,Mode,Variance,Standard Deviation,Skewness,Kurtosis
Size,-0.503015,-0.513703,-7.151703,3.717410,1.928059,-0.002437,-0.083341
Weight,-0.989547,-0.984736,-7.149848,2.568029,1.602507,0.003102,0.359050
Crunchiness,0.985478,0.998249,-6.055058,1.967728,1.402757,0.000230,0.722020
Juiciness,0.512118,0.534219,-5.961897,3.726003,1.930286,-0.113421,0.028735
Ripeness,0.498277,0.503445,-5.864599,3.513476,1.874427,-0.008764,-0.071850